### ISSUE TITLE
Builder error: unsupported pair

### ISSUE THREAD

**Issue by alpha-tango-kilo** [Lutetium-Vanadium/requestty#1]
Hi there!

First of all, thank you for the crate! It's a lovely simple way to start interacting with users in the terminal

I have the following function:

```rust
pub fn get_api_key(client: &reqwest::blocking::Client) -> Result<String> {
    let question = Question::input("api_key")
        .message("Please enter in your OMDb API key. If you need to, visit their website to get one (https://www.omdbapi.com/apikey.aspx)")
        .validate(|api_key, _| test_api_key(api_key, client))
        .build();
    Ok(requestty::prompt_one(question)?.try_into_string().unwrap())
}
```

It compiles fine, however regardless as to what the user inputs (and whether or not it should be valid), I get the error `builder error: unsupported pair`.

I can't work out what I'm doing to cause the error, any pointers?

**Comment by Lutetium-Vanadium** [comment]
Hi, thanks for your kind words!

In the [`Display` impl for  `reqwest::Error`](https://github.com/seanmonstar/reqwest/blob/c6eb2c4fcbc3934b119772e0997d91671ff68dc7/src/error.rs#L174), you can see where it prints "builder error". The error would be coming from some interaction with the `reqwest` crate (probably somewhere in `test_api_key`), so I'm not sure how I can help.

**Comment by alpha-tango-kilo** [comment]
Ugh I'm an idiot, I did search through your crate to try and find the error in the source and couldn't find it - and this would be why. Sorry for the hassle
