### ISSUE TITLE
dbg code in 0.4.0

### ISSUE THREAD

**Issue by anewton1998** [Lutetium-Vanadium/requestty#12]
Using version 0.4.0 on Ubuntu linux, I see the following when inputting data for prompts:

```
[/home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/requestty-ui-0.4.0/src/input.rs:125] self.backend.size() = Ok(
                                                                                                                              Size {
                                                                                                                                            width: 372,
                                                                                                                                                               height: 74,
                                                                                                                                                                              },
                                                                                                                                                                                )

```

This appears to come from a `dbg!` on line 125 of input.rs. That sends the message to stderr. I'm using Gnome terminal, but it also happens with xterm. Oddly, this does not happen in rxvt or the vs-code terminal.

It's probably best to remove this line, as the rust docs say:

> The dbg! macro works exactly the same in release builds. This is useful when debugging issues that only occur in release builds or when debugging in release mode is significantly faster.
> 
> Note that the macro is intended as a debugging tool and therefore you should avoid having uses of it in version control for long periods (other than in tests and similar). Debug output from production code is better done with other facilities such as the [debug!](https://docs.rs/log/*/log/macro.debug.html) macro from the [log](https://crates.io/crates/log) crate.

**Comment by anewton1998** [comment]
Just an update, it doesn't seem to matter which console I use. Once the text needs to start scrolling then the dbg message is printed.

**Comment by Lutetium-Vanadium** [comment]
Good catch! I'll release a patch shortly
