### ISSUE TITLE
Bugs with wide characters (like CJK)

### ISSUE THREAD

**Issue by Guyutongxue** [Lutetium-Vanadium/requestty#19]
Most CJK characters are as wide as two ASCII characters; they should also take up twice the width on the terminal.

Therefore, if you pass CJK characters into the prompt or input when using this library, the cursor position will be abnormal.

```rust
use requestty::*;

fn main() -> Result<()> {
    prompt_one(
        Question::input("name")
            .message("你叫什么名字")
            .default("王小明")
            .build(),
    )?;
    Ok(())
}

```

![image](https://user-images.githubusercontent.com/33127223/185729541-df84e7c9-a22c-4575-8576-049ccc6d9f43.png)

**Comment by Guyutongxue** [comment]
Sorry, maybe a duplicate of #18. Close this if needed.

**Comment by Lutetium-Vanadium** [comment]
Thanks for bringing up this issue. It has been fixed now
