### ISSUE TITLE
Incorrect cursor location when input prompt spans multiple lines

### ISSUE THREAD

**Issue by alpha-tango-kilo** [Lutetium-Vanadium/requestty#2]
Hi there! Hopefully this is actually an issue with this library, unlike the last issue I raised 🙈

If a free text input prompt spans multiple lines, the cursor shows in the correct position horizontally, but on the first line of the prompt, like so:

![image](https://user-images.githubusercontent.com/12728900/136420677-cd49a362-3cbe-466c-bd92-0858512cf74f.png)

(Notice the underscore on the "u" in "your")

Typing input moves the cursor horizontally as expected, but it remains on the first line as opposed to where the input actually is

Tested on Windows & Linux, issue present on both

**Comment by Lutetium-Vanadium** [comment]
Hi! This is indeed a bug with this library. I will push a fix soon

**Comment by Lutetium-Vanadium** [comment]
I have published the fix. Please check and close the issue if it works fine
