### ISSUE TITLE
Greyed-out text for the first autocompletion

### ISSUE THREAD

**Issue by nitnelave** [Lutetium-Vanadium/requestty#4]
Hello,

Is it possible to have some fish-style greyed-out autocompletions with the first autocompletion? Like https://fishshell.com/assets/img/screenshots/autosuggestion.png
Then tab would autocomplete to that (while still doing what it's currently doing, cycling through the possibilities of course). It would just be a display change.

That would help the user know that they can autocomplete.

**Comment by Lutetium-Vanadium** [comment]
I get what you mean, but I don't think I want to implement it for auto-completions. However, this is a great way to show the `default`

**Comment by nitnelave** [comment]
If you gave me a few pointers, I could give it a shot.

**Comment by Lutetium-Vanadium** [comment]
I meant it more in terms of I didn't want to change the current behaviour of auto-complete. Currently, if you are going through the auto-completions shown, it shows the option selected as the full input text which is more indicative of the fact that if the user starts typing regular characters, it extends from the auto-complete option they were hovering.

I have already changed the default is shown as I mentioned before, so there isn't anything to do anymore. Thanks for the interest in implementing it!
