### ISSUE TITLE
EditorBuilder: Change Editor Programatically

### ISSUE THREAD

**Issue by buck-ross** [Lutetium-Vanadium/requestty#8]
# Feature Request

I'm trying to use this library to write a set of applications designed for use with git, and I would really like to be able to allow users to configure which editor the application launches via git's own `core.editor` configuration value. I already have the necessary code in place to extract the value of `core.editor` as a string, but there doesn't seem to be a way to change the preferred editor when using `EditorBuilder`.

I don't think I'm the only person who would find this feature useful. Lots of applications provide their own configuration scheme, which should take precedence over the value of `$VISUAL` and `$EDITOR`.

From what I can tell, this should be a simple feature to add; you would just need to add a new mutation method to the [`EditorBuilder`](https://github.com/Lutetium-Vanadium/requestty/blob/master/src/question/editor.rs#L208) class, which would allow the user to set the value of `self.editor.editor` to some arbitrary string.  The end result would be something like this:

```rust
use requestty::Question;

let preferred_editor: String = get_preferred_editor_from_my_config_file();

let editor = Question::editor("description")
    .message("Please enter a short description about yourself")
    // This next line is the feature I'm requesting:
    .prefer_editor(preferred_editor)
    .build();
```

That said, I'm still fairly new to rust, so please let me know if this could be more difficult than I'm thinking.

Assuming this feature request isn't met with any push-back, I would be happy to try writing this myself, and will submit a PR if and when I've made significant progress.

Thank you for your time!

**Comment by Lutetium-Vanadium** [comment]
Hi! Sorry for the long delay, but this sounds like a great feature. The preferred editor being a `Command` makes more sense to me, as that is the `std` interface for running programs. If you'd like to write a PR I'll be more than happy to review it, otherwise I will get to it for the next version :)
